version: '2'
services:
    radar-rest-source-auth-backend:
        image: radarbase/radar-rest-source-auth-backend:1.1.0
        networks:
          - default
        depends_on:
          - auth-postgresql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgresql:5432/restsourceauth
            - SPRING_DATASOURCE_USERNAME=radarcns
            - SPRING_DATASOURCE_PASSWORD=radarcns
            - REST_SOURCE_AUTHORIZER_SOURCE_CLIENTS_FILE_PATH=app-includes/rest_source_clients_configs.yml
            - APP_SLEEP=10 # gives time for the database to boot before the application
        volumes:
            - ./etc:/app-includes
    auth-postgresql:
        image: postgres:10.4-alpine
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=radarcns
          - POSTGRES_PASSWORD=radarcns
          - POSTGRES_DB=restsourceauth
#
#    radar-rest-source-authorizer:
#        image: radarbase/radar-rest-source-authorizer:latest
#        depends_on:
#          - radar-rest-source-auth-backend
#          - auth-postgresql
#        ports:
#          - "3000:80"
