service:
  # Interval time in minutes for syncing projects and subjects.
  baseUri: http://0.0.0.0:8085/rest-sources/backend/
  advertisedBaseUri: http://0.0.0.0:8080/rest-sources/backend/
  enableCors: true

auth:
  # Management Portal URL
  managementPortalUrl: http://managementportal-app:8080/managementportal/
  # OAuth2 Client id of more-promasys-sync application
  clientId: radar_rest_sources_auth_backend
  # OAuth2 Client Secret of more_promasys_sync_client client
  clientSecret: secret

database:
  jdbcDriver: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://radarbase-postgresql:5432/uploadconnector
  jdbcUser: radarcns
  jdbcPassword: radarcns
  hibernateDialect: org.hibernate.dialect.PostgreSQLDialect

restSourceClients:
  - sourceType: FitBit
    authorizationEndpoint: https://www.fitbit.com/oauth2/authorize
    tokenEndpoint: https://api.fitbit.com/oauth2/token
    clientId: Fitbit-clientid
    clientSecret: Fitbit-clientsecret
    scope: activity heartrate sleep profile
